<?php

/**
 * @file
 * Contains \Drupal\render_cache\Tests\Plugin\ContainerAwarePluginManagerTest
 */

namespace Drupal\render_cache\Tests\Plugin;

use Drupal\render_cache\DependencyInjection\Container;
use Drupal\render_cache\DependencyInjection\ContainerInterface;
use Drupal\render_cache\Plugin\ContainerAwarePluginManager;

use Mockery;

/**
 * @coversDefaultClass \Drupal\render_cache\Plugin\ContainerAwarePluginManager
 * @group dic
 */
class ContainerAwarePluginManagerTest extends \PHPUnit_Framework_TestCase {
 
  /**
   * {@inheritdoc}
   */
  public function setUp() {
    $this->containerDefinition = $this->getContainerDefinition();
    $this->container = new Container($this->containerDefinition);
    $this->controllerPluginManager = $this->container->get('render_cache.controller');
  }

  /**
   * Tests that CachedContainerBuilder::isCached() works properly.
   */
  public function test_getDefinition() {
    $this->assertEquals($this->containerDefinition['services']['render_cache.controller.internal.block'], $this->controllerPluginManager->getDefinition('block'), 'render_cache.controller.internal.block definition matches.');
  }

  public function test_getDefinitions() {
    $filtered_definitions = array(
      'render_cache.controller.internal.block' => $this->containerDefinition['services']['render_cache.controller.internal.block'],
    );
    $this->assertEquals($filtered_definitions, $this->controllerPluginManager->getDefinitions(), 'getDefinitions() returns only definitions matching the prefix.');
  }

  public function test_hasDefinition() {
    $this->assertTrue($this->controllerPluginManager->hasDefinition('block'), 'render_cache.controller.internal.block definition exists.');
    $this->assertFalse($this->controllerPluginManager->hasDefinition('not_exists'), 'render_cache.controller.internal.not_exists definition exists not.');
  }

  public function test_createInstance() {
    $block_controller = $this->controllerPluginManager->createInstance('block');
    $this->assertInstanceof('\Drupal\render_cache_block\RenderCache\Controller\BlockController', $block_controller, 'createInstance() returns the right class.');
    $block_controller2 = $this->controllerPluginManager->createInstance('block');
    $this->assertNotSame($block_controller, $block_controller2, 'createInstance() returns not the same instance when called twice.');
  }

  /**
   * Returns a container definition used for testing.
   *
   * @return array
   *   The container definition with services and parameters.
   */
  protected function getContainerDefinition() {
    $parameters = array();

    $services = array();
    $services['service_container'] = array(
      'class' => '\Drupal\render_cache\DependencyInjection\Container',
    );
    $services['render_cache.controller'] = array(
      'class' => '\Drupal\render_cache\Plugin\ContainerAwarePluginManager',
      'arguments' => array('render_cache.controller.internal.'),
      'calls' => array(
        array('setContainer', array('@service_container')),
      ),
      'tags' => array(
        array('ctools.plugin', array(
          'owner' => 'render_cache',
          'type' => 'controller',
          'prefix' => 'render_cache.controller.internal.')
        ),
      ),
    );
    // This would have been autogenerated by the ctools.plugin tag definition.
    $services['render_cache.controller.internal.block'] = array(
      'class' => '\Drupal\render_cache_block\RenderCache\Controller\BlockController',
      'arguments' => array(
         array(
          'name' => 'Block',
        ),
      ),
      'public' => FALSE,
    );

    return array(
      'parameters' => $parameters,
      'services' => $services,
    );
  }
}
